name: UI Tests

on:
  workflow_dispatch:

jobs:
  test-chrome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: action/setup-python@v7
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Run UI tests (Chrome)
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          EXIYING_USER_EMAIL: ${{secrets.EXIYING_USER_EMAIL}}
          EXIYING_USER_PASSWORD: ${{secrets.EXIYING_USER_PASSWORD}}
        run: pytest tests/test_login.py --browser=chrome --headless --alluredir=allure-results

      - name: Upload diagnostics (Chrome)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chrome-diagnostics
          path: |
            logs/
            screenshots/
            allure-results/
          if-no-files-found: ignore


  test-firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: action/setup-python@v7
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Run UI tests (Firefox)
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          EXIYING_USER_EMAIL: ${{secrets.EXIYING_USER_EMAIL}}
          EXIYING_USER_PASSWORD: ${{secrets.EXIYING_USER_PASSWORD}}
        run: pytest tests/test_login.py --browser=firefox --headless --alluredir=allure-results

      - name: Upload diagnostics (Firefox)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firefox-diagnostics
          path: |
            logs/
            screenshots/
            allure-results/
          if-no-files-found: ignore
